server.port=8080

jwt.secret=${JWT_SECRET:viet-history-rag-secret-key-2024}


spring.cloud.gateway.routes[0].id=auth-route
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.routes[1].id=user-route
spring.cloud.gateway.routes[1].uri=http://localhost:8081
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/users/**

spring.cloud.gateway.routes[2].id=chat-route
spring.cloud.gateway.routes[2].uri=http://localhost:8082
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/chat/**

spring.cloud.gateway.routes[3].id=ai-route
spring.cloud.gateway.routes[3].uri=http://localhost:8001
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/ai/**
spring.cloud.gateway.routes[4].id=dynasty-route
spring.cloud.gateway.routes[4].uri=http://localhost:8001
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/dynasties/**

logging.level.org.springframework.cloud.gateway=INFO
logging.level.com.vietnamhistory.apigateway=DEBUG
