server.port=8082

# Database
spring.datasource.url=${CHAT_DB_URL}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

spring.main.web-application-type=servlet

# AI Service
ai.service.url=${AI_SERVICE_URL:http://ai-service:8001}

# Jackson
spring.jackson.serialization.write-dates-as-timestamps=false
